<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>cfg</string>
    </array>
    <key>name</key>
    <string>Buildout Config</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.buildout</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^(#).*$\n?</string>
            <key>name</key>
            <string>comment.line.number-sign.buildout</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.buildout</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^(;).*$\n?</string>
            <key>name</key>
            <string>comment.line.semicolon.buildout</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.definition.buildout</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^([a-zA-Z0-9_.-]+)\b\s*(=|\+=)</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^recipe\s*=\s*(.*)$</string>
            <key>name</key>
            <string>constant.numeric.recipe.buildout</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\[(.*?)\]</string>
            <key>name</key>
            <string>entity.other.attribute-name.group-title.buildout</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\$\{(.*?):(.*?)}</string>
            <key>name</key>
            <string>constant.language.reference.buildout</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.buildout</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.buildout</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.buildout</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\.</string>
                    <key>name</key>
                    <string>constant.character.escape.buildout</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.buildout</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.buildout</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.buildout</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.buildout</string>
    <key>uuid</key>
    <string>28542624-1060-4D30-8D70-6F6CCCD65B1E</string>
</dict>
</plist>
