<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
	</array>
	<key>name</key>
	<string>HTML (Django)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>{% comment %}</string>
			<key>end</key>
			<string>{% endcomment %}</string>
			<key>name</key>
			<string>comment.block.django</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{#</string>
			<key>end</key>
			<string>#}</string>
			<key>name</key>
			<string>comment.line.number-sign.django</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.tag.tagbraces.django</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>storage.type.variable.django</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#template_filter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{%</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.tag.tagbraces.django</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%}</string>
			<key>name</key>
			<string>storage.type.templatetag.django</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#template_tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#template_filter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>template_filter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(add|addslashes|capfirst|center|cut|date|default|default_if_none|dictsort|dictsortreversed|divisibleby|escape|escapejs|filesizeformat|first|fix_ampersands|floatformat|force_escape|get_digit|iriencode|join|last|length|length_is|linebreaks|linebreaksbr|linenumbers|ljust|lower|make_list|phone2numeric|pluralize|pprint|random|removetags|rjust|safe|safeseq|slice|slugify|stringformat|striptags|time|timesince|timeutil|title|truncatewords|truncatewords_html|unordered_list|upper|urlencode|urlize|urlizetrunc|wordcount|wordwrap|yesno|apnumber|intcomma|intword|naturalday|ordinal|STATIC_PREFIX)\b</string>
					<key>name</key>
					<string>keyword.control.filter.django</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:"|"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>storage.type.attr.django</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:\'|\'</string>
					<key>end</key>
					<string>\'</string>
					<key>name</key>
					<string>storage.type.attr.django</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>string.unquoted.filter-pipe.django</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z0-9_.]+</string>
					<key>name</key>
					<string>string.unquoted.tag-string.django</string>
				</dict>
			</array>
		</dict>
		<key>template_tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(autoescape|endautoescape|block|endblock|blocktrans|endblocktrans|trans|plural|debug|extends|filter|firstof|for|empty|endfor|if|elif|else|endif|include|ifchanged|endifchanged|ifequal|endifequal|ifnotequal|endifnotequal|load|from|low|regroup|ssi|spaceless|endspaceless|templatetag|widthratio|with|endwith|csrf_token|cycle|url|lorem|thumbnail|endthumbnail|get_static_prefix)\b</string>
					<key>name</key>
					<string>keyword.control.tag-name.django</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(and|or|not|in|by|as)\b</string>
					<key>name</key>
					<string>keyword.operator.django</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.django</string>
</dict>
</plist>
